version: "3.8"
services:
  redis:
    image: redis:7.2.2-alpine
    restart: on-failure
  mongodb:
    image: mongo:7.0.2
    restart: on-failure
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    image: openagents-frontend
    volumes:
      - "frontend-data:/app/data"
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongodb
      - backend
  backend:
    build: ./
    image: openagents-backend
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongodb
    environment:
      - OPENAI_API_KEY=""
      # - KAGGLE_USER=
      # - KAGGLE_KEY=
      # - OPENAI_API_BASE=
volumes:
  frontend-data:
    driver: local

